In [22]:
import pandas as pd
import numpy as np
import os

In [23]:
os.chdir('C:\\Users\\DELL\\Desktop\\Data Framing\\classification')

In [24]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [25]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    11021175    Male   42           121315          0
1    17782313    Male   53            67214          0
2    14603818  Female   59           111005          0
3    18188198  Female   39            53414          0
4    19357305    Male   39           114285          0
5    19524602    Male   39           107458          0
6    19455396  Female   20            85582          0
7    16879913  Female   59           148335          1
8    11838352    Male   48            80579          0
9    13118940  Female   42           114204          0
10   19524480  Female   32            87786          0
11   12784093  Female   49           113544          0
12   12895966    Male   55            88300          0
13   14674114    Male   54           147066          0
14   12393248    Male   57           139622          0
15   18842131    Male   41           134716          0
16   11060500    Male   51           116333          1
17   14887406    Male   55            72567          1
18   12606442    Male   44           123254          1
19   17919323  Female   47           113548          1
20   17207101    Male   52            79343          1
21   17159912  Female   20           106149          1
22   10718832    Male   40            59674          1
23   16952550  Female   52            76333          1
24   10494682    Male   28           118742          1
25   16824758    Male   22           105897          1
26   11168323    Male   25           114815          1
27   16945283  Female   38            85428          1
28   13865670    Male   57           114005          0
29   16924204    Male   57           133402          0
..        ...     ...  ...              ...        ...
370  10974769  Female   53            91670          1
371  15997078    Male   39            91484          1
372  15543007  Female   38            79015          0
373  12045512    Male   47           105738          1
374  18148680  Female   60           149376          0
375  19389802  Female   32           132339          1
376  14176702  Female   55            65263          0
377  16272022  Female   43           121151          0
378  13867391    Male   55           143658          1
379  14220159  Female   39           107871          1
380  14988491    Male   35            88727          0
381  13839143    Male   55            78055          1
382  13739543  Female   36            58593          1
383  16476895    Male   27            62004          1
384  16144247  Female   51            99881          1
385  19172097    Male   42            72411          1
386  15679010  Female   47            91721          1
387  12372850    Male   34           140775          0
388  18431004    Male   35            79146          1
389  17054280  Female   58           128623          1
390  18333359    Male   25           128311          1
391  13980301    Male   23            72896          1
392  15750258  Female   57           115969          1
393  19695633    Male   28           111173          1
394  13806266  Female   41           107820          0
395  10220446  Female   20           141231          1
396  12387292    Male   50            75848          1
397  10715173  Female   25            82560          1
398  10016842    Male   55           147667          0
399  11699655  Female   54           134972          1

[400 rows x 5 columns]

In [26]:
dataset.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [27]:
x = dataset.iloc[:,2:4].values
x

array([[    42, 121315],
       [    53,  67214],
       [    59, 111005],
       [    39,  53414],
       [    39, 114285],
       [    39, 107458],
       [    20,  85582],
       [    59, 148335],
       [    48,  80579],
       [    42, 114204],
       [    32,  87786],
       [    49, 113544],
       [    55,  88300],
       [    54, 147066],
       [    57, 139622],
       [    41, 134716],
       [    51, 116333],
       [    55,  72567],
       [    44, 123254],
       [    47, 113548],
       [    52,  79343],
       [    20, 106149],
       [    40,  59674],
       [    52,  76333],
       [    28, 118742],
       [    22, 105897],
       [    25, 114815],
       [    38,  85428],
       [    57, 114005],
       [    57, 133402],
       [    43, 106726],
       [    35,  84550],
       [    34,  96296],
       [    32,  68964],
       [    55,  90946],
       [    48,  51787],
       [    22,  53940],
       [    42, 138928],
       [    59, 116474],
       [    23,  97284],
       [    40, 132951],
       [    24, 119308],
       [    50, 120675],
       [    41, 113547],
       [    52, 102686],
       [    34, 140262],
       [    20,  54075],
       [    25,  63715],
       [    46,  56058],
       [    58,  65052],
       [    38,  72107],
       [    21, 108656],
       [    42, 120639],
       [    31,  68033],
       [    26,  80283],
       [    47,  60952],
       [    31, 123137],
       [    36,  98529],
       [    25, 121301],
       [    28,  61144],
       [    41, 107405],
       [    32,  87032],
       [    53, 118544],
       [    38,  63743],
       [    43,  53404],
       [    34,  88672],
       [    29,  96164],
       [    47, 123288],
       [    31, 122623],
       [    31,  78696],
       [    51, 142525],
       [    59,  87656],
       [    29, 142587],
       [    25, 136561],
       [    59, 146860],
       [    60, 142362],
       [    35,  69596],
       [    26,  68131],
       [    36, 110448],
       [    23,  83386],
       [    58, 108578],
       [    30, 141388],
       [    43, 149365],
       [    56,  58313],
       [    51, 102619],
       [    28,  55147],
       [    41,  50075],
       [    34, 107704],
       [    43, 114836],
       [    47, 121827],
       [    34,  81442],
       [    34, 107339],
       [    26, 112221],
       [    45,  95625],
       [    57, 122153],
       [    51,  95670],
       [    34, 143045],
       [    59, 137848],
       [    36,  52183],
       [    36,  79634],
       [    23, 113567],
       [    54, 141579],
       [    37,  65595],
       [    36, 112290],
       [    34,  81496],
       [    50, 149336],
       [    40,  75308],
       [    52, 100654],
       [    41, 126711],
       [    40, 108120],
       [    49, 105753],
       [    20, 136968],
       [    24,  93042],
       [    28, 123123],
       [    20,  82371],
       [    23, 124432],
       [    39,  77263],
       [    42,  74062],
       [    56,  66914],
       [    20, 135880],
       [    56, 141015],
       [    47,  56095],
       [    54, 105953],
       [    31, 134226],
       [    40, 140382],
       [    52,  83150],
       [    43, 134224],
       [    45,  56858],
       [    58,  78749],
       [    30,  85067],
       [    32, 126056],
       [    25, 113954],
       [    48,  95856],
       [    33,  97459],
       [    47, 135037],
       [    26, 119179],
       [    54, 149039],
       [    45,  82604],
       [    58, 141603],
       [    54,  78694],
       [    57, 124533],
       [    50, 131911],
       [    41,  59001],
       [    46, 121055],
       [    56, 129867],
       [    29,  92841],
       [    30,  52952],
       [    37, 110760],
       [    26, 118184],
       [    33, 112314],
       [    41,  89916],
       [    30, 121311],
       [    35,  89632],
       [    45, 100855],
       [    43,  65553],
       [    54,  53506],
       [    52,  52428],
       [    58,  82785],
       [    30,  53649],
       [    22,  87705],
       [    52,  89220],
       [    46, 144559],
       [    56, 100871],
       [    25, 144076],
       [    22,  92835],
       [    42, 143855],
       [    40, 134666],
       [    58,  60780],
       [    38,  71907],
       [    53, 117339],
       [    24,  59930],
       [    45,  81582],
       [    43, 105079],
       [    54,  89483],
       [    30, 101011],
       [    24,  63875],
       [    43,  78367],
       [    34,  98157],
       [    21,  67195],
       [    27,  60011],
       [    43,  85692],
       [    31, 122030],
       [    35, 111404],
       [    51, 112365],
       [    24, 145116],
       [    53,  84777],
       [    24, 117799],
       [    49, 123887],
       [    37, 110617],
       [    39,  66443],
       [    28,  74078],
       [    34,  53024],
       [    45,  60629],
       [    38,  96053],
       [    37, 115700],
       [    32, 149553],
       [    22,  54897],
       [    57, 106814],
       [    26,  82215],
       [    34,  97989],
       [    34, 129656],
       [    48,  54293],
       [    41, 115121],
       [    47,  58050],
       [    32, 106526],
       [    31,  66259],
       [    56, 114193],
       [    32,  93654],
       [    30,  90905],
       [    32,  87630],
       [    23,  57412],
       [    35, 138992],
       [    55,  79423],
       [    23,  58900],
       [    32,  79811],
       [    42,  73731],
       [    45,  97845],
       [    46, 124974],
       [    25, 126831],
       [    29, 129796],
       [    44, 113742],
       [    46, 140395],
       [    33,  96753],
       [    25,  73636],
       [    54, 131776],
       [    53, 115173],
       [    23, 132989],
       [    55,  78749],
       [    26, 114306],
       [    29, 144160],
       [    59,  73810],
       [    45,  69716],
       [    52, 103076],
       [    31, 120701],
       [    43,  88766],
       [    51, 145365],
       [    39, 100402],
       [    33, 133440],
       [    28,  79496],
       [    42,  59216],
       [    23,  59666],
       [    28,  96148],
       [    57, 104693],
       [    38, 125226],
       [    25,  64832],
       [    44, 147276],
       [    36,  51894],
       [    46,  87539],
       [    44, 123166],
       [    58,  80730],
       [    52,  61880],
       [    55,  55940],
       [    36,  83172],
       [    57,  62224],
       [    29,  85752],
       [    21,  92044],
       [    58, 114689],
       [    25,  75753],
       [    39, 147108],
       [    27, 116149],
       [    41,  76066],
       [    28, 139815],
       [    51,  89365],
       [    30,  96984],
       [    45,  83469],
       [    43, 123902],
       [    31, 103674],
       [    25, 149284],
       [    55, 101685],
       [    29,  84375],
       [    59,  80400],
       [    35, 116617],
       [    48,  63697],
       [    23, 125328],
       [    31, 115264],
       [    22,  52203],
       [    55,  79300],
       [    24, 118146],
       [    45, 118915],
       [    32, 145807],
       [    25,  89964],
       [    57, 100193],
       [    59,  51243],
       [    59,  96999],
       [    51, 120749],
       [    47,  90983],
       [    38,  66879],
       [    59,  56930],
       [    60,  74753],
       [    24, 142544],
       [    56,  71895],
       [    39, 138840],
       [    36,  73233],
       [    37, 144858],
       [    37, 137622],
       [    20,  61919],
       [    59,  83724],
       [    50, 114793],
       [    51, 117179],
       [    60,  64051],
       [    35,  56687],
       [    57, 101429],
       [    43,  74931],
       [    27,  71384],
       [    30, 130926],
       [    22, 111072],
       [    57, 137143],
       [    37,  65536],
       [    25,  89304],
       [    23, 140900],
       [    50, 136552],
       [    54,  75491],
       [    52,  71429],
       [    59,  81753],
       [    44,  95919],
       [    47, 108041],
       [    29,  83561],
       [    47, 118252],
       [    52,  74847],
       [    25,  58866],
       [    38,  64972],
       [    20,  64957],
       [    22, 111361],
       [    43,  91205],
       [    41,  65781],
       [    32, 126318],
       [    23, 140167],
       [    28,  94239],
       [    52, 125189],
       [    52,  63103],
       [    40, 107099],
       [    49,  59438],
       [    36, 134882],
       [    28,  58789],
       [    37, 145025],
       [    22, 146149],
       [    31, 127446],
       [    39,  83401],
       [    21, 123460],
       [    51,  64207],
       [    49, 128666],
       [    48, 120137],
       [    28,  80299],
       [    30, 104548],
       [    24, 138809],
       [    42, 130324],
       [    59, 139963],
       [    60,  72905],
       [    51,  52093],
       [    36, 119778],
       [    33,  86617],
       [    29,  69997],
       [    21,  89174],
       [    44, 143222],
       [    29, 130705],
       [    59,  80220],
       [    28, 119752],
       [    21,  76043],
       [    44, 145967],
       [    25,  79824],
       [    43,  89982],
       [    46, 147530],
       [    36,  60575],
       [    43,  78098],
       [    55,  81409],
       [    28,  70948],
       [    50, 104297],
       [    48, 127871],
       [    33, 126297],
       [    24, 110968],
       [    53,  91670],
       [    39,  91484],
       [    38,  79015],
       [    47, 105738],
       [    60, 149376],
       [    32, 132339],
       [    55,  65263],
       [    43, 121151],
       [    55, 143658],
       [    39, 107871],
       [    35,  88727],
       [    55,  78055],
       [    36,  58593],
       [    27,  62004],
       [    51,  99881],
       [    42,  72411],
       [    47,  91721],
       [    34, 140775],
       [    35,  79146],
       [    58, 128623],
       [    25, 128311],
       [    23,  72896],
       [    57, 115969],
       [    28, 111173],
       [    41, 107820],
       [    20, 141231],
       [    50,  75848],
       [    25,  82560],
       [    55, 147667],
       [    54, 134972]], dtype=int64)

In [28]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x = sc_x.fit_transform(x)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [29]:
x

array([[ 0.17951354,  0.76103154],
       [ 1.11315372, -1.14804259],
       [ 1.622412  ,  0.39722026],
       [-0.0751156 , -1.63500628],
       [-0.0751156 ,  0.51296235],
       [-0.0751156 ,  0.27205647],
       [-1.68776681, -0.49988685],
       [ 1.622412  ,  1.71449234],
       [ 0.68877182, -0.67642883],
       [ 0.17951354,  0.51010409],
       [-0.66925025, -0.42211381],
       [ 0.7736482 ,  0.48681452],
       [ 1.28290648, -0.40397617],
       [ 1.1980301 ,  1.66971285],
       [ 1.45265924,  1.40703476],
       [ 0.09463716,  1.23391563],
       [ 0.94340096,  0.58523059],
       [ 1.28290648, -0.95915007],
       [ 0.3492663 ,  0.82945347],
       [ 0.60389544,  0.48695567],
       [ 1.02827734, -0.72004384],
       [-1.68776681,  0.2258655 ],
       [ 0.00976078, -1.41410826],
       [ 1.02827734, -0.82625839],
       [-1.00875577,  0.67023751],
       [-1.51801405,  0.21697311],
       [-1.26338491,  0.53166458],
       [-0.15999198, -0.50532108],
       [ 1.45265924,  0.50308193],
       [ 1.45265924,  1.18754822],
       [ 0.26438992,  0.24622622],
       [-0.41462111, -0.53630326],
       [-0.49949749, -0.12181953],
       [-0.66925025, -1.08628994],
       [ 1.28290648, -0.31060618],
       [ 0.68877182, -1.6924186 ],
       [-1.51801405, -1.6164452 ],
       [ 0.17951354,  1.38254542],
       [ 1.622412  ,  0.59020609],
       [-1.43313767, -0.08695575],
       [ 0.00976078,  1.17163368],
       [-1.34826129,  0.69021008],
       [ 0.85852458,  0.73844772],
       [ 0.09463716,  0.48692038],
       [ 1.02827734,  0.10366584],
       [-0.49949749,  1.42961858],
       [-1.68776681, -1.61168143],
       [-1.26338491, -1.27151258],
       [ 0.51901906, -1.54170686],
       [ 1.53753562, -1.22433356],
       [-0.15999198, -0.9753822 ],
       [-1.60289043,  0.31433057],
       [ 0.17951354,  0.73717738],
       [-0.75412663, -1.11914235],
       [-1.17850853, -0.68687385],
       [ 0.60389544, -1.36901118],
       [-0.75412663,  0.82532486],
       [-0.32974473, -0.04302315],
       [-1.26338491,  0.76053752],
       [-1.00875577, -1.36223604],
       [ 0.09463716,  0.27018625],
       [-0.66925025, -0.44872037],
       [ 1.11315372,  0.66325064],
       [-0.15999198, -1.27052454],
       [ 0.26438992, -1.63535915],
       [-0.49949749, -0.39084932],
       [-0.92387939, -0.12647744],
       [ 0.60389544,  0.83065323],
       [-0.75412663,  0.80718723],
       [-0.75412663, -0.74287468],
       [ 0.94340096,  1.50947357],
       [ 1.622412  , -0.42670114],
       [-0.92387939,  1.51166138],
       [-1.26338491,  1.29902056],
       [ 1.622412  ,  1.66244369],
       [ 1.70728837,  1.50372175],
       [-0.41462111, -1.06398842],
       [-1.17850853, -1.1156842 ],
       [-0.32974473,  0.37756527],
       [-1.43313767, -0.57737759],
       [ 1.53753562,  0.31157816],
       [-0.83900301,  1.46935199],
       [ 0.26438992,  1.75083818],
       [ 1.36778286, -1.46213417],
       [ 0.94340096,  0.10130159],
       [-1.00875577, -1.57385352],
       [ 0.09463716, -1.75283032],
       [-0.49949749,  0.28073713],
       [ 0.26438992,  0.53240561],
       [ 0.60389544,  0.7790986 ],
       [-0.49949749, -0.64597596],
       [-0.49949749,  0.26785729],
       [-1.17850853,  0.44012952],
       [ 0.43414268, -0.14549725],
       [ 1.45265924,  0.79060223],
       [ 0.94340096, -0.14390933],
       [-0.49949749,  1.52782293],
       [ 1.622412  ,  1.34443522],
       [-0.32974473, -1.67844485],
       [-0.32974473, -0.70977526],
       [-1.43313767,  0.48762613],
       [ 1.1980301 ,  1.47609185],
       [-0.24486835, -1.2051726 ],
       [-0.32974473,  0.44256434],
       [-0.49949749, -0.64407045],
       [ 0.85852458,  1.74981485],
       [ 0.00976078, -0.86242779],
       [ 1.02827734,  0.0319622 ],
       [ 0.09463716,  0.9514414 ],
       [ 0.00976078,  0.29541661],
       [ 0.7736482 ,  0.21189175],
       [-1.68776681,  1.31338246],
       [-1.34826129, -0.23664415],
       [-1.00875577,  0.82483084],
       [-1.68776681, -0.61319413],
       [-1.43313767,  0.87102182],
       [-0.0751156 , -0.79344127],
       [ 0.17951354, -0.90639567],
       [ 1.36778286, -1.15862875],
       [-1.68776681,  1.27498996],
       [ 1.36778286,  1.45618986],
       [ 0.60389544, -1.54040123],
       [ 1.1980301 ,  0.2189492 ],
       [-0.75412663,  1.21662489],
       [ 0.00976078,  1.43385305],
       [ 1.02827734, -0.58570538],
       [ 0.26438992,  1.21655432],
       [ 0.43414268, -1.51347708],
       [ 1.53753562, -0.74100445],
       [-0.83900301, -0.51805977],
       [-0.66925025,  0.92832827],
       [-1.26338491,  0.50128228],
       [ 0.68877182, -0.13734591],
       [-0.58437387, -0.08078048],
       [ 0.60389544,  1.24524283],
       [-1.17850853,  0.68565803],
       [ 1.1980301 ,  1.73933455],
       [ 0.43414268, -0.6049722 ],
       [ 1.53753562,  1.47693875],
       [ 1.1980301 , -0.74294525],
       [ 1.45265924,  0.87458583],
       [ 0.85852458,  1.13493497],
       [ 0.09463716, -1.43785656],
       [ 0.51901906,  0.75185686],
       [ 1.36778286,  1.06280788],
       [-0.92387939, -0.24373689],
       [-0.83900301, -1.65130898],
       [-0.24486835,  0.38857489],
       [-1.17850853,  0.65054724],
       [-0.58437387,  0.44341123],
       [ 0.09463716, -0.34695202],
       [-0.83900301,  0.76089039],
       [-0.41462111, -0.35697359],
       [ 0.43414268,  0.03905493],
       [ 0.26438992, -1.20665466],
       [ 1.1980301 , -1.63175986],
       [ 1.02827734, -1.66979948],
       [ 1.53753562, -0.59858521],
       [-0.83900301, -1.62671378],
       [-1.51801405, -0.42497207],
       [ 1.02827734, -0.37151193],
       [ 0.51901906,  1.58124778],
       [ 1.36778286,  0.03961953],
       [-1.26338491,  1.56420405],
       [-1.51801405, -0.24394861],
       [ 0.17951354,  1.55640558],
       [ 0.00976078,  1.23215127],
       [ 1.53753562, -1.37508059],
       [-0.15999198, -0.98243964],
       [ 1.11315372,  0.62072954],
       [-1.34826129, -1.40507473],
       [ 0.43414268, -0.64103575],
       [ 0.26438992,  0.18810817],
       [ 1.1980301 , -0.36223139],
       [-0.83900301,  0.04455974],
       [-1.34826129, -1.26586663],
       [ 0.26438992, -0.75448417],
       [-0.49949749, -0.05615   ],
       [-1.60289043, -1.14871304],
       [-1.09363215, -1.40221646],
       [ 0.26438992, -0.49600525],
       [-0.75412663,  0.78626191],
       [-0.41462111,  0.41129986],
       [ 0.94340096,  0.44521088],
       [-1.34826129,  1.60090277],
       [ 1.11315372, -0.52829306],
       [-1.34826129,  0.63696166],
       [ 0.7736482 ,  0.85179028],
       [-0.24486835,  0.38352881],
       [-0.0751156 , -1.17524904],
       [-1.00875577, -0.90583108],
       [-0.49949749, -1.6487683 ],
       [ 0.43414268, -1.38040896],
       [-0.15999198, -0.13039432],
       [-0.24486835,  0.56289378],
       [-0.66925025,  1.75747218],
       [-1.51801405, -1.58267533],
       [ 1.45265924,  0.2493315 ],
       [-1.17850853, -0.61869893],
       [-0.49949749, -0.06207826],
       [-0.49949749,  1.05536228],
       [ 0.68877182, -1.60398881],
       [ 0.09463716,  0.54246247],
       [ 0.60389544, -1.47141471],
       [-0.66925025,  0.23916878],
       [-0.75412663, -1.18174188],
       [ 1.36778286,  0.50971593],
       [-0.66925025, -0.21504837],
       [-0.83900301, -0.31205295],
       [-0.66925025, -0.42761861],
       [-1.43313767, -1.49392796],
       [-0.41462111,  1.3848038 ],
       [ 1.28290648, -0.71722086],
       [-1.43313767, -1.44142057],
       [-0.66925025, -0.70352942],
       [ 0.17951354, -0.91807574],
       [ 0.43414268, -0.06715962],
       [ 0.51901906,  0.89014749],
       [-1.26338491,  0.95567587],
       [-0.92387939,  1.06030249],
       [ 0.3492663 ,  0.49380139],
       [ 0.51901906,  1.43431178],
       [-0.58437387, -0.10569326],
       [-1.26338491, -0.92142803],
       [ 1.1980301 ,  1.13017119],
       [ 1.11315372,  0.54429741],
       [-1.43313767,  1.1729746 ],
       [ 1.28290648, -0.74100445],
       [-1.17850853,  0.51370338],
       [-0.92387939,  1.56716818],
       [ 1.622412  , -0.91528805],
       [ 0.43414268, -1.05975395],
       [ 1.02827734,  0.11742785],
       [-0.75412663,  0.73936518],
       [ 0.26438992, -0.38753233],
       [ 0.94340096,  1.60968929],
       [-0.0751156 ,  0.02306982],
       [-0.58437387,  1.18888914],
       [-1.00875577, -0.7146449 ],
       [ 0.17951354, -1.43026981],
       [-1.43313767, -1.41439055],
       [-1.00875577, -0.12704204],
       [ 1.45265924,  0.1744873 ],
       [-0.15999198,  0.89903987],
       [-1.26338491, -1.23209675],
       [ 0.3492663 ,  1.67712317],
       [-0.32974473, -1.68864286],
       [ 0.51901906, -0.43082975],
       [ 0.3492663 ,  0.82634819],
       [ 1.53753562, -0.67110046],
       [ 1.02827734, -1.33626464],
       [ 1.28290648, -1.54587075],
       [-0.32974473, -0.58492906],
       [ 1.45265924, -1.32412583],
       [-0.92387939, -0.49388802],
       [-1.60289043, -0.2718608 ],
       [ 1.53753562,  0.52721839],
       [-1.26338491, -0.84672498],
       [-0.0751156 ,  1.67119492],
       [-1.09363215,  0.57873774],
       [ 0.09463716, -0.83568008],
       [-1.00875577,  1.41384519],
       [ 0.94340096, -0.36639528],
       [-0.83900301, -0.09754192],
       [ 0.43414268, -0.57444875],
       [ 0.26438992,  0.85231959],
       [-0.75412663,  0.13852961],
       [-1.26338491,  1.74797992],
       [ 1.28290648,  0.06834333],
       [-0.92387939, -0.54247853],
       [ 1.622412  , -0.68274524],
       [-0.41462111,  0.59525216],
       [ 0.68877182, -1.27214775],
       [-1.43313767,  0.90263917],
       [-0.75412663,  0.54750855],
       [-1.51801405, -1.67773911],
       [ 1.28290648, -0.72156119],
       [-1.34826129,  0.64920633],
       [ 0.43414268,  0.6763422 ],
       [-0.66925025,  1.62528624],
       [-1.26338491, -0.34525823],
       [ 1.45265924,  0.01569479],
       [ 1.622412  , -1.71161485],
       [ 1.622412  , -0.09701261],
       [ 0.94340096,  0.74105897],
       [ 0.60389544, -0.30930055],
       [-0.15999198, -1.15986381],
       [ 1.622412  , -1.5109364 ],
       [ 1.70728837, -0.8820122 ],
       [-1.34826129,  1.51014403],
       [ 1.36778286, -0.98286309],
       [-0.0751156 ,  1.37944015],
       [-0.32974473, -0.93564878],
       [-0.24486835,  1.59179866],
       [-0.24486835,  1.33646031],
       [-1.68776681, -1.33488844],
       [ 1.622412  , -0.56545051],
       [ 0.85852458,  0.53088826],
       [ 0.94340096,  0.61508358],
       [ 1.70728837, -1.25965608],
       [-0.41462111, -1.5195112 ],
       [ 1.45265924,  0.0593098 ],
       [ 0.26438992, -0.87573107],
       [-1.09363215, -1.00089486],
       [-0.83900301,  1.10017705],
       [-1.51801405,  0.3995845 ],
       [ 1.45265924,  1.31955773],
       [-0.24486835, -1.20725455],
       [-1.26338491, -0.3685478 ],
       [-1.43313767,  1.45213183],
       [ 0.85852458,  1.29870298],
       [ 1.1980301 , -0.85597023],
       [ 1.02827734, -0.99930693],
       [ 1.622412  , -0.63500163],
       [ 0.3492663 , -0.13512281],
       [ 0.60389544,  0.29262892],
       [-0.92387939, -0.57120233],
       [ 0.60389544,  0.65294677],
       [ 1.02827734, -0.8786952 ],
       [-1.26338491, -1.44262033],
       [-0.15999198, -1.22715654],
       [-1.68776681, -1.22768585],
       [-1.51801405,  0.40978251],
       [ 0.26438992, -0.30146679],
       [ 0.09463716, -1.19860918],
       [-0.66925025,  0.93757352],
       [-1.43313767,  1.42626629],
       [-1.00875577, -0.19440535],
       [ 1.02827734,  0.89773425],
       [ 1.02827734, -1.29310836],
       [ 0.00976078,  0.25938836],
       [ 0.7736482 , -1.42243604],
       [-0.32974473,  1.23977331],
       [-1.00875577, -1.44533745],
       [-0.24486835,  1.59769163],
       [-1.51801405,  1.63735447],
       [-0.75412663,  0.97737751],
       [-0.0751156 , -0.57684828],
       [-1.60289043,  0.83672264],
       [ 0.94340096, -1.25415127],
       [ 0.7736482 ,  1.02042793],
       [ 0.68877182,  0.71946319],
       [-1.00875577, -0.68630925],
       [-0.83900301,  0.16937065],
       [-1.34826129,  1.37834624],
       [ 0.17951354,  1.07893414],
       [ 1.622412  ,  1.4190677 ],
       [ 1.70728837, -0.94722299],
       [ 0.94340096, -1.6816207 ],
       [-0.32974473,  0.70679508],
       [-0.58437387, -0.46336457],
       [-0.92387939, -1.04983824],
       [-1.60289043, -0.37313514],
       [ 0.3492663 ,  1.53406876],
       [-0.92387939,  1.09237858],
       [ 1.622412  , -0.68909695],
       [-1.00875577,  0.70587761],
       [-1.60289043, -0.83649168],
       [ 0.3492663 ,  1.63093219],
       [-1.26338491, -0.70307069],
       [ 0.26438992, -0.34462306],
       [ 0.51901906,  1.68608613],
       [-0.32974473, -1.38231447],
       [ 0.26438992, -0.76397644],
       [ 1.28290648, -0.64714044],
       [-1.00875577, -1.01628009],
       [ 0.85852458,  0.16051356],
       [ 0.68877182,  0.99237458],
       [-0.58437387,  0.93683249],
       [-1.34826129,  0.39591463],
       [ 1.11315372, -0.28505823],
       [-0.0751156 , -0.29162165],
       [-0.15999198, -0.73161805],
       [ 0.60389544,  0.21136245],
       [ 1.70728837,  1.75122634],
       [-0.66925025,  1.1500379 ],
       [ 1.28290648, -1.21688796],
       [ 0.26438992,  0.75524444],
       [ 1.28290648,  1.54945399],
       [-0.0751156 ,  0.2866301 ],
       [-0.41462111, -0.38890853],
       [ 1.28290648, -0.76549379],
       [-0.32974473, -1.45225375],
       [-1.09363215, -1.33188902],
       [ 0.94340096,  0.00468517],
       [ 0.17951354, -0.96465488],
       [ 0.60389544, -0.28325858],
       [-0.49949749,  1.44772093],
       [-0.41462111, -0.72699542],
       [ 1.53753562,  1.01891058],
       [-1.26338491,  1.00790096],
       [-1.43313767, -0.94754058],
       [ 1.45265924,  0.57238604],
       [-1.00875577,  0.40314851],
       [ 0.09463716,  0.28483045],
       [-1.68776681,  1.4638119 ],
       [ 0.85852458, -0.84337269],
       [-1.26338491, -0.60652484],
       [ 1.28290648,  1.69092048],
       [ 1.1980301 ,  1.24294916]])

In [30]:
 y = dataset.iloc[:,4].values

In [31]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1], dtype=int64)

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [33]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [34]:
y_pred = logmodel.predict(x_test)

In [35]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [36]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[56,  0],
       [24,  0]], dtype=int64)

In [37]:
y_pred = logmodel.predict(x)

In [38]:
dataset_new = dataset.drop(['Purchased'], axis=1)
dataset_new

      User ID  Gender  Age  EstimatedSalary
0    11021175    Male   42           121315
1    17782313    Male   53            67214
2    14603818  Female   59           111005
3    18188198  Female   39            53414
4    19357305    Male   39           114285
5    19524602    Male   39           107458
6    19455396  Female   20            85582
7    16879913  Female   59           148335
8    11838352    Male   48            80579
9    13118940  Female   42           114204
10   19524480  Female   32            87786
11   12784093  Female   49           113544
12   12895966    Male   55            88300
13   14674114    Male   54           147066
14   12393248    Male   57           139622
15   18842131    Male   41           134716
16   11060500    Male   51           116333
17   14887406    Male   55            72567
18   12606442    Male   44           123254
19   17919323  Female   47           113548
20   17207101    Male   52            79343
21   17159912  Female   20           106149
22   10718832    Male   40            59674
23   16952550  Female   52            76333
24   10494682    Male   28           118742
25   16824758    Male   22           105897
26   11168323    Male   25           114815
27   16945283  Female   38            85428
28   13865670    Male   57           114005
29   16924204    Male   57           133402
..        ...     ...  ...              ...
370  10974769  Female   53            91670
371  15997078    Male   39            91484
372  15543007  Female   38            79015
373  12045512    Male   47           105738
374  18148680  Female   60           149376
375  19389802  Female   32           132339
376  14176702  Female   55            65263
377  16272022  Female   43           121151
378  13867391    Male   55           143658
379  14220159  Female   39           107871
380  14988491    Male   35            88727
381  13839143    Male   55            78055
382  13739543  Female   36            58593
383  16476895    Male   27            62004
384  16144247  Female   51            99881
385  19172097    Male   42            72411
386  15679010  Female   47            91721
387  12372850    Male   34           140775
388  18431004    Male   35            79146
389  17054280  Female   58           128623
390  18333359    Male   25           128311
391  13980301    Male   23            72896
392  15750258  Female   57           115969
393  19695633    Male   28           111173
394  13806266  Female   41           107820
395  10220446  Female   20           141231
396  12387292    Male   50            75848
397  10715173  Female   25            82560
398  10016842    Male   55           147667
399  11699655  Female   54           134972

[400 rows x 4 columns]

In [39]:
y_pred = pd.DataFrame(y).rename(columns={0:"Purchased"})
y_pred

     Purchased
0            0
1            0
2            0
3            0
4            0
5            0
6            0
7            1
8            0
9            0
10           0
11           0
12           0
13           0
14           0
15           0
16           1
17           1
18           1
19           1
20           1
21           1
22           1
23           1
24           1
25           1
26           1
27           1
28           0
29           0
..         ...
370          1
371          1
372          0
373          1
374          0
375          1
376          0
377          0
378          1
379          1
380          0
381          1
382          1
383          1
384          1
385          1
386          1
387          0
388          1
389          1
390          1
391          1
392          1
393          1
394          0
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [40]:
dataset_new = pd.concat([dataset_new,y_pred], axis=1)
dataset_new

      User ID  Gender  Age  EstimatedSalary  Purchased
0    11021175    Male   42           121315          0
1    17782313    Male   53            67214          0
2    14603818  Female   59           111005          0
3    18188198  Female   39            53414          0
4    19357305    Male   39           114285          0
5    19524602    Male   39           107458          0
6    19455396  Female   20            85582          0
7    16879913  Female   59           148335          1
8    11838352    Male   48            80579          0
9    13118940  Female   42           114204          0
10   19524480  Female   32            87786          0
11   12784093  Female   49           113544          0
12   12895966    Male   55            88300          0
13   14674114    Male   54           147066          0
14   12393248    Male   57           139622          0
15   18842131    Male   41           134716          0
16   11060500    Male   51           116333          1
17   14887406    Male   55            72567          1
18   12606442    Male   44           123254          1
19   17919323  Female   47           113548          1
20   17207101    Male   52            79343          1
21   17159912  Female   20           106149          1
22   10718832    Male   40            59674          1
23   16952550  Female   52            76333          1
24   10494682    Male   28           118742          1
25   16824758    Male   22           105897          1
26   11168323    Male   25           114815          1
27   16945283  Female   38            85428          1
28   13865670    Male   57           114005          0
29   16924204    Male   57           133402          0
..        ...     ...  ...              ...        ...
370  10974769  Female   53            91670          1
371  15997078    Male   39            91484          1
372  15543007  Female   38            79015          0
373  12045512    Male   47           105738          1
374  18148680  Female   60           149376          0
375  19389802  Female   32           132339          1
376  14176702  Female   55            65263          0
377  16272022  Female   43           121151          0
378  13867391    Male   55           143658          1
379  14220159  Female   39           107871          1
380  14988491    Male   35            88727          0
381  13839143    Male   55            78055          1
382  13739543  Female   36            58593          1
383  16476895    Male   27            62004          1
384  16144247  Female   51            99881          1
385  19172097    Male   42            72411          1
386  15679010  Female   47            91721          1
387  12372850    Male   34           140775          0
388  18431004    Male   35            79146          1
389  17054280  Female   58           128623          1
390  18333359    Male   25           128311          1
391  13980301    Male   23            72896          1
392  15750258  Female   57           115969          1
393  19695633    Male   28           111173          1
394  13806266  Female   41           107820          0
395  10220446  Female   20           141231          1
396  12387292    Male   50            75848          1
397  10715173  Female   25            82560          1
398  10016842    Male   55           147667          0
399  11699655  Female   54           134972          1

[400 rows x 5 columns]

In [ ]:
dataset_new.to_csv('Pred_DataSet_outpu.csv')